<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `classroom-ddd` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Application\Group\Query;

final class GetGroupById extends \Prooph\Common\Messaging\Query
{
    use \Prooph\Common\Messaging\PayloadTrait;

    public const MESSAGE_NAME = 'App\Application\Group\Query\GetGroupById';

    protected $messageName = self::MESSAGE_NAME;

    public function groupId(): \App\Domain\Group\Model\GroupId
    {
        return \App\Domain\Group\Model\GroupId::fromString($this->payload['groupId']);
    }

    public static function with(\App\Domain\Group\Model\GroupId $groupId): GetGroupById
    {
        return new self([
            'groupId' => $groupId->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['groupId']) || !\is_string($payload['groupId'])) {
            throw new \InvalidArgumentException("Key 'groupId' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
