<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `classroom-ddd` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Application\Professor\Query;

final class GetProfessorByUsername extends \Prooph\Common\Messaging\Query
{
    use \Prooph\Common\Messaging\PayloadTrait;

    public const MESSAGE_NAME = 'App\Application\Professor\Query\GetProfessorByUsername';

    protected $messageName = self::MESSAGE_NAME;

    public function username(): \App\Domain\Common\Model\Username
    {
        return \App\Domain\Common\Model\Username::fromString($this->payload['username']);
    }

    public static function with(\App\Domain\Common\Model\Username $username): GetProfessorByUsername
    {
        return new self([
            'username' => $username->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['username']) || !\is_string($payload['username'])) {
            throw new \InvalidArgumentException("Key 'username' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
