<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `classroom-ddd` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Application\Professor\Command;

final class AddProfessor extends \Prooph\Common\Messaging\Command
{
    use \Prooph\Common\Messaging\PayloadTrait;

    public const MESSAGE_NAME = 'App\Application\Professor\Command\AddProfessor';

    protected $messageName = self::MESSAGE_NAME;

    public function professorId(): \App\Domain\Professor\Model\ProfessorId
    {
        return \App\Domain\Professor\Model\ProfessorId::fromString($this->payload['professorId']);
    }

    public function username(): \App\Domain\Common\Model\Username
    {
        return \App\Domain\Common\Model\Username::fromString($this->payload['username']);
    }

    public function password(): \App\Domain\Common\Model\Password
    {
        return \App\Domain\Common\Model\Password::fromString($this->payload['password']);
    }

    public function role(): \App\Domain\Professor\Model\ProfessorRole
    {
        return \App\Domain\Professor\Model\ProfessorRole::fromName($this->payload['role']);
    }

    public static function with(\App\Domain\Professor\Model\ProfessorId $professorId, \App\Domain\Common\Model\Username $username, \App\Domain\Common\Model\Password $password, \App\Domain\Professor\Model\ProfessorRole $role): AddProfessor
    {
        return new self([
            'professorId' => $professorId->toString(),
            'username' => $username->toString(),
            'password' => $password->toString(),
            'role' => $role->name(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['professorId']) || !\is_string($payload['professorId'])) {
            throw new \InvalidArgumentException("Key 'professorId' is missing in payload or is not a string");
        }

        if (!isset($payload['username']) || !\is_string($payload['username'])) {
            throw new \InvalidArgumentException("Key 'username' is missing in payload or is not a string");
        }

        if (!isset($payload['password']) || !\is_string($payload['password'])) {
            throw new \InvalidArgumentException("Key 'password' is missing in payload or is not a string");
        }

        if (!isset($payload['role']) || !\is_string($payload['role'])) {
            throw new \InvalidArgumentException("Key 'role' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
