<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `classroom-ddd` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Domain\Student\Event;

final class StudentWasAdded extends \Prooph\EventSourcing\AggregateChanged
{
    public const MESSAGE_NAME = 'App\Domain\Student\Event\StudentWasAdded';

    protected $messageName = self::MESSAGE_NAME;

    protected $payload = [];

    private $studentId;
    private $cardNumber;
    private $person;

    public function studentId(): \App\Domain\Student\Model\StudentId
    {
        if (null === $this->studentId) {
            $this->studentId = \App\Domain\Student\Model\StudentId::fromString($this->aggregateId());
        }

        return $this->studentId;
    }

    public function cardNumber(): \App\Domain\Student\Model\StudentCardNumber
    {
        if (null === $this->cardNumber) {
            $this->cardNumber = \App\Domain\Student\Model\StudentCardNumber::fromString($this->payload['cardNumber']);
        }

        return $this->cardNumber;
    }

    public function person(): \App\Domain\Common\Model\Person
    {
        if (null === $this->person) {
            $this->person = \App\Domain\Common\Model\Person::fromArray($this->payload['person']);
        }

        return $this->person;
    }

    public static function with(\App\Domain\Student\Model\StudentId $studentId, \App\Domain\Student\Model\StudentCardNumber $cardNumber, \App\Domain\Common\Model\Person $person): StudentWasAdded
    {
        return new self($studentId->toString(), [
            'cardNumber' => $cardNumber->toString(),
            'person' => $person->toArray(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['cardNumber']) || !\is_string($payload['cardNumber'])) {
            throw new \InvalidArgumentException("Key 'cardNumber' is missing in payload or is not a string");
        }

        if (!isset($payload['person']) || !\is_array($payload['person'])) {
            throw new \InvalidArgumentException("Key 'person' is missing in payload or is not an array");
        }

        $this->payload = $payload;
    }
}
