<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `classroom-ddd` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Domain\Student\Event;

final class StudentWasRemoved extends \Prooph\EventSourcing\AggregateChanged
{
    public const MESSAGE_NAME = 'App\Domain\Student\Event\StudentWasRemoved';

    protected $messageName = self::MESSAGE_NAME;

    protected $payload = [];

    private $studentId;

    public function studentId(): \App\Domain\Student\Model\StudentId
    {
        if (null === $this->studentId) {
            $this->studentId = \App\Domain\Student\Model\StudentId::fromString($this->aggregateId());
        }

        return $this->studentId;
    }

    public static function with(\App\Domain\Student\Model\StudentId $studentId): StudentWasRemoved
    {
        return new self($studentId->toString(), [
        ]);
    }

    protected function setPayload(array $payload): void
    {
        $this->payload = $payload;
    }
}
