<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `classroom-ddd` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Application\Group\Command;

final class AddGroup extends \Prooph\EventSourcing\AggregateChanged
{
    public const MESSAGE_NAME = 'App\Application\Group\Command\AddGroup';

    protected $messageName = self::MESSAGE_NAME;

    protected $payload = [];

    private $groupId;
    private $groupName;

    public function groupId(): \App\Domain\Group\Model\GroupId
    {
        if (null === $this->groupId) {
            $this->groupId = \App\Domain\Group\Model\GroupId::fromString($this->aggregateId());
        }

        return $this->groupId;
    }

    public function groupName(): \App\Domain\Group\Model\GroupName
    {
        if (null === $this->groupName) {
            $this->groupName = \App\Domain\Group\Model\GroupName::fromString($this->payload['groupName']);
        }

        return $this->groupName;
    }

    public static function with(\App\Domain\Group\Model\GroupId $groupId, \App\Domain\Group\Model\GroupName $groupName): AddGroup
    {
        return new self($groupId->toString(), [
            'groupName' => $groupName->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['groupName']) || !\is_string($payload['groupName'])) {
            throw new \InvalidArgumentException("Key 'groupName' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
