<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `classroom-ddd` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Domain\Common\Model;

final class Person
{
    private $firstName;
    private $lastName;
    private $age;

    public function __construct(FirstName $firstName, LastName $lastName, Age $age)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->age = $age;
    }

    public function firstName(): FirstName
    {
        return $this->firstName;
    }

    public function lastName(): LastName
    {
        return $this->lastName;
    }

    public function age(): Age
    {
        return $this->age;
    }

    public function withFirstName(FirstName $firstName): Person
    {
        return new self($firstName, $this->lastName, $this->age);
    }

    public function withLastName(LastName $lastName): Person
    {
        return new self($this->firstName, $lastName, $this->age);
    }

    public function withAge(Age $age): Person
    {
        return new self($this->firstName, $this->lastName, $age);
    }

    public static function fromArray(array $data): Person
    {
        if (!isset($data['firstName']) || !\is_string($data['firstName'])) {
            throw new \InvalidArgumentException("Key 'firstName' is missing in data array or is not a string");
        }

        $firstName = FirstName::fromString($data['firstName']);

        if (!isset($data['lastName']) || !\is_string($data['lastName'])) {
            throw new \InvalidArgumentException("Key 'lastName' is missing in data array or is not a string");
        }

        $lastName = LastName::fromString($data['lastName']);

        if (!isset($data['age']) || !\is_int($data['age'])) {
            throw new \InvalidArgumentException("Key 'age' is missing in data array or is not a int");
        }

        $age = Age::fromScalar($data['age']);

        return new self(
            $firstName,
            $lastName,
            $age
        );
    }

    public function toArray(): array
    {
        return [
            'firstName' => $this->firstName->toString(),
            'lastName' => $this->lastName->toString(),
            'age' => $this->age->toScalar(),
        ];
    }
}
