<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `classroom-ddd` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Application\Student\Command;

final class AddStudent extends \Prooph\Common\Messaging\Command
{
    use \Prooph\Common\Messaging\PayloadTrait;

    public const MESSAGE_NAME = 'App\Application\Student\Command\AddStudent';

    protected $messageName = self::MESSAGE_NAME;

    public function studentId(): \App\Domain\Student\Model\StudentId
    {
        return \App\Domain\Student\Model\StudentId::fromString($this->payload['studentId']);
    }

    public function cardNumber(): \App\Domain\Student\Model\StudentCardNumber
    {
        return \App\Domain\Student\Model\StudentCardNumber::fromString($this->payload['cardNumber']);
    }

    public function person(): \App\Domain\Common\Model\Person
    {
        return \App\Domain\Common\Model\Person::fromArray($this->payload['person']);
    }

    public static function with(\App\Domain\Student\Model\StudentId $studentId, \App\Domain\Student\Model\StudentCardNumber $cardNumber, \App\Domain\Common\Model\Person $person): AddStudent
    {
        return new self([
            'studentId' => $studentId->toString(),
            'cardNumber' => $cardNumber->toString(),
            'person' => $person->toArray(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['studentId']) || !\is_string($payload['studentId'])) {
            throw new \InvalidArgumentException("Key 'studentId' is missing in payload or is not a string");
        }

        if (!isset($payload['cardNumber']) || !\is_string($payload['cardNumber'])) {
            throw new \InvalidArgumentException("Key 'cardNumber' is missing in payload or is not a string");
        }

        if (!isset($payload['person']) || !\is_array($payload['person'])) {
            throw new \InvalidArgumentException("Key 'person' is missing in payload or is not an array");
        }

        $this->payload = $payload;
    }
}
