<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `classroom-ddd` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Application\Student\Command;

final class RemoveStudent extends \Prooph\Common\Messaging\Command
{
    use \Prooph\Common\Messaging\PayloadTrait;

    public const MESSAGE_NAME = 'App\Application\Student\Command\RemoveStudent';

    protected $messageName = self::MESSAGE_NAME;

    public function studentId(): \App\Domain\Student\Model\StudentId
    {
        return \App\Domain\Student\Model\StudentId::fromString($this->payload['studentId']);
    }

    public static function with(\App\Domain\Student\Model\StudentId $studentId): RemoveStudent
    {
        return new self([
            'studentId' => $studentId->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['studentId']) || !\is_string($payload['studentId'])) {
            throw new \InvalidArgumentException("Key 'studentId' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
