<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

/*
 * This file is part of the `classroom-ddd` project.
 *
 * (c) Aula de Software Libre de la UCO <aulasoftwarelibre@uco.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Domain\Student\Model;

final class StudentId
{
    private $uuid;

    public static function generate(): StudentId
    {
        return new self(\Ramsey\Uuid\Uuid::uuid4());
    }

    public static function fromString(string $studentId): StudentId
    {
        return new self(\Ramsey\Uuid\Uuid::fromString($studentId));
    }

    private function __construct(\Ramsey\Uuid\UuidInterface $studentId)
    {
        $this->uuid = $studentId;
    }

    public function toString(): string
    {
        return $this->uuid->toString();
    }

    public function __toString(): string
    {
        return $this->uuid->toString();
    }

    public function equals(StudentId $other): bool
    {
        return $this->uuid->equals($other->uuid);
    }
}
